# Generated by Django 2.0 on 2018-07-21 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('author', models.CharField(max_length=10)),
                ('text', models.CharField(max_length=200)),
                ('img', models.ImageField(upload_to='image')),
                ('file', models.FileField(upload_to='file')),
            ],
        ),
        migrations.CreateModel(
            name='Read_Num',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_num_data', models.IntegerField()),
                ('article', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.Article')),
            ],
        ),
    ]
