# Generated by Django 2.0.6 on 2018-06-19 10:30

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20180619_0757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
