# Generated by Django 2.0.6 on 2018-06-19 11:02

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20180619_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
