# Generated by Django 2.0 on 2018-07-15 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReadNumber', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='readnum',
            name='read_num',
            field=models.IntegerField(default=0),
        ),
    ]
