# Generated by Django 2.0 on 2018-07-15 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='read_num',
            old_name='read_num',
            new_name='read_num_data',
        ),
    ]
