# Generated by Django 2.0 on 2018-08-04 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recent_Read', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recent_read',
            options={'ordering': ['-Read_time']},
        ),
        migrations.AddField(
            model_name='recent_read',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
    ]
