# Generated by Django 2.0 on 2018-07-21 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='file',
            new_name='file_upload',
        ),
    ]
