# Generated by Django 2.0 on 2018-07-27 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20180721_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='file_upload',
            field=models.FileField(blank=True, upload_to='file'),
        ),
        migrations.AlterField(
            model_name='article',
            name='img',
            field=models.ImageField(blank=True, upload_to='image'),
        ),
    ]
