# Generated by Django 2.0 on 2018-08-15 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Attitude', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attitudecount',
            old_name='attitude_applause_num',
            new_name='attitude_flower_num',
        ),
    ]
